### PR TITLE
Add live updating between synced devices

### PR DESCRIPTION
**Pull request by seren**
This adds `Plugin.onExternalSettingsChange` support, as described in https://github.com/tgrosinger/recent-files-obsidian/issues/46 and  https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#v157.

### CODE REVIEW

**Comment by seren** [comment]
Let me know if there's anything I should change. Thanks.

**Comment by tgrosinger** [comment]
Thanks @seren for the changes!

**Comment by jamie9090** [comment]
Hello! How soon does this sync? On mobile, I do not seem to see the recent files from desktop :) 

Cheers!

**Comment by seren** [comment]
Have you quit and restarted the mobile app after updating the plugin? And are you using Obisidian Sync?

**Pull request merged**
