### PR TITLE
Full refactoring

### PR DESCRIPTION
**Pull request by 3C0D**
I used NodeNext and adapted the config to it. 
Most recent push about tag included. 
the code has been entirely checked and some little points improved

### CODE REVIEW

**Comment by 3C0D** [comment]
I adapted the previous eslint config without any change in it

**Comment by tgrosinger** [comment]
Hello,
Could you please provide some details about what problems you are solving in this refactor, and why such a large refactor is necessary?

Generally it would be polite to engage with the project maintainer before undertaking such a large change. A complete refactoring of a project with no clear problem being solved is very unlikely to be merged.

If there are more targeted improvements you would like to suggest, please feel free to open a new pull request with just those changes as well as an explanation of what is being changed, why it needs to be changed, and how you tested the changes.

Thank you.

**Comment by 3C0D** [comment]
Hello,

I appreciate your feedback, though I must admit it caught me off guard. The refactor was something I undertook without specific expectations, as I felt a full restructuring was necessary for the codebase to be clearer and more maintainable.

The changes I made are more structural than functional, with only a few minor code adjustments such as fixing forgotten await statements or removing unused CSS classes. I didn’t approach it step-by-step, because doing so would have tied me to the original code, making it harder to create a clean and well-structured outcome. I understand that reviewing such a large change is challenging, but breaking it down file-by-file might help clarify the improvements made.

I’m aware that the base configuration has changed slightly, but it's still possible to revert to the old setup if desired. Adjustments can be made, for instance, using VSCode to auto-regenerate imports, if the original configuration is preferred. I’m suggesting some changes, like switching to Node Next, but of course, I’m not claiming to be an expert on everything—there’s always room for improvement, and I’m open to collaboration.

I realize this may involve extra work, but the refactor as a whole brings more clarity and structure to the code. It wasn’t done out of ego or to follow any imposed rules, but from a genuine desire to improve the project. If there are parts you feel strongly about, I’m happy to discuss and adjust, but I wanted to take a holistic approach to the refactor to avoid piecemeal changes that wouldn’t provide the same clarity.

Feel free to use or discard what you see fit—my contribution is simply an offer to help improve the project.

Thank you for your time.

**Comment by 3C0D** [comment]
I wonder who is not polite now...

**Comment by zayKenyon** [comment]
> I wonder who is not polite now...

You, still. Don't complain about service you're not paying for!

**Comment by seren** [comment]
Doing code review is time consuming, especially a large refactor, so it's understandable that maintainers don't want to spend their limited time to review changes for things that aren't broken.

This is especially true now that open source projects have to be vigilant of supply chain attackers trying to insert malicious code into projects (the recent xz backdoor being the  most public of these). 

Improving the maintainability and structure of a code base through refactoring is good, but is best done with the blessing of the maintainer(s) since it may introduce conflicting coding styles or conventions.

So don't take this PR's lack of acceptance as a slight, but rather a reminder to see what a project needs and what kind of help the community or maintainer could use. You obviously know the Obsidian plugin system pretty well, so maybe you could make a new one, or add a requested feature to an existing one?

**Pull request closed without merging**
